name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Install Flutter
        uses: subosito/flutter-action@v2

      - name: Get Flutter packages
        run: flutter pub get

      - name: Run unit tests
        run: flutter test

      - name: Run integration tests
        run: |
          # Avvia l'emulatore Android
          sudo $ANDROID_SDK_ROOT/emulator/emulator -avd test -no-snapshot -no-audio -no-window &
          EMULATOR_PID=$!
          # Attendi che l'emulatore sia avviato
          flutter emulators --launch test
          flutter devices
          # Avvia l'applicazione in modalità debug
          flutter run --machine --target test_driver/integration_test.dart --device-id emulator-5554 > log.txt 2>&1 &
          FLUTTER_PID=$!
          # Attendi un po' per assicurarti che l'applicazione sia avviata
          sleep 30
          # Ottieni l'URL del servizio VM dai log
          VM_SERVICE_URL=$(grep -o 'http://127.0.0.1:[0-9]*/' log.txt)
          echo "VM_SERVICE_URL=$VM_SERVICE_URL" >> $GITHUB_ENV
          # Esegui i test di integrazione
          flutter drive --target=test_driver/integration_test.dart
          # Termina l'applicazione Flutter
          kill $FLUTTER_PID
          # Termina l'emulatore
          kill $EMULATOR_PID

      - name: Build Flutter app for release
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-${{ github.run_number }}
          path: build/app/outputs/flutter-apk/app-release.apk
