name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Install dependencies
        run: sudo apt-get install -y cmake ninja-build clang libgtk-3-dev

      - name: Install Flutter
        uses: subosito/flutter-action@v2

      - name: Get Flutter packages
        run: flutter pub get

      - name: Upgrade Flutter packages
        run: flutter pub upgrade

      - name: Enable Flutter Linux desktop
        run: flutter config --enable-linux-desktop

      - name: Run unit tests
        run: flutter test

      - name: Run integration tests
        run: flutter test integration_test/app_test.dart -d linux --no-sound-null-safety

      - name: Build Flutter app for release
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-${{ github.run_number }}
          path: build/app/outputs/flutter-apk/app-release.apk
